# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- master


stages:
- stage: Build
  displayName: Build stage
  jobs:  
  - job: Build
    displayName: Build job
    pool: default

    steps:
    - script: echo Hello, world!
      displayName: 'Run a one-line script'

    - script: |
        echo Add other tasks to build, test, and deploy your project.
        echo See https://aka.ms/yaml
      displayName: 'Run a multi-line script'

    - task: Docker@2
      inputs:
        containerRegistry: '9a75d994-437a-4f04-9a8b-c0ce686eb876'
        repository: 'atulmakshelm'
        command: 'buildAndPush'
        Dockerfile: '**/Dockerfile'
    
    - script: |
     #!/bin/bash
     docker container create --name nodeapp $(imageName)
     docker cp nodeapp:/test-routes.xml $(System.DefaultWorkingDirectory)
     #docker cp nodeapp:/usr/src/app/coverage $(System.DefaultWorkingDirectory)
    displayName: Script