apiVersion : apps/v1beta1
kind: Deployment
metadata:
  name: roopeshnairexpressaks 
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: roopeshnairexpressaks 
    spec:
      containers:
        - name: roopeshnairexpressaks 
          image: ronacr.azurecr.io/roopeshnairexpressaks
          ports:
          - containerPort: 3000